application: robinchorus
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: server/assets/img/favicon.ico
  upload: server/assets//img/favicon.ico

- url: /robots.txt
  static_files: server/assets/robots.txt
  upload: server/assets/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /server/assets/css/*
  mime_type: text/css
  static_dir: server/assets/css

- url: /server/assets/js/*
  mime_type: text/javascript
  static_dir: server/assets/js

- url: /server/assets/*
  static_dir: server/assets

- url: .*
  script: run.server.app